# Generated by Django 5.1 on 2024-08-26 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_alter_proyecto_fecha_inicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Consultas',
        ),
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Servicios',
        ),
    ]
